### ISSUE TITLE
IMM Review

### ISSUE THREAD

**Issue by idg10** [corvus-dotnet/Corvus.Identity#44]
Go through every item on the IP Maturity Matrix and ensure it is up to date, adding work items in any areas that could be improved

- [x] **Shared Engineering Standards**
- [x] **Coding Standards**
- [x] **Executable Specifications** #66
- [x] **Code Coverage**
- [x] **Benchmarks** #63
- [x] **Reference Documentation**
- [x] **Design & Implementation Documentation** #64
- [x] **How-to Documentation** #65
- [x] **Date of Last IP Review**
- [x] **Framework Version**
- [x] **Associated Work Items** #67
- [x] **Source Code Availability**
- [x] **License**: Apache 2.0
- [x] **Production Use**
- [x] **Insights** #68
- [x] **Packaging** #69
- [x] **Deployment**
- [x] **Next IMM review** #70
